Lesson 8
DarkSou1/PacharmProjects pull request #2
Opened 2021-12-09 18:36 UTC by DarkSou1

Hi, I'm sending you a new branch for review.

2021-12-09 21:36 UTC, okunevkirill reviewed
Остальные задачу проверю позднее

2021-12-09 21:36 UTC, okunevkirill commented on lesson_8/task_1.py
> +def email_parse(email_adress):
Всё таки: `email_address`

2021-12-09 21:36 UTC, okunevkirill commented on lesson_8/task_1.py
> +    RE_EMAIL = re.compile(r'^([\w\.]+@)+([\w-]+)+(\.+[\w-]{2,4})$')
Не очень удачное регулярное выражение для email, - как минимум она пропускает цифры в качестве домена.
>Ниже приведу альтернативу

2021-12-09 21:36 UTC, okunevkirill commented on lesson_8/task_1.py
> +    if RE_EMAIL.match(email_adress) is not None:
Зачем `... is note None`?
Хватило бы такого условия:
```
if RE_EMAIL.match(email_adress):
```

2021-12-09 21:36 UTC, okunevkirill commented on lesson_8/task_1.py
> +        email_split = email_adress.split('@')
Данной строкой делаешь излишние операции - можно было пользоваться особенностью регулярок и `match`

2021-12-09 21:36 UTC, okunevkirill commented on lesson_8/task_1.py
> +
Альтернативное решение на основе твоего:
```
def email_parse_alt(email_address):
    result_dict = {}
    RE_EMAIL = re.compile(r'^([\w]+)@+([\w-]+\.[a-zA-Z]{2,4})$')
    groups = RE_EMAIL.match(email_address)
    if groups:
        result_dict['username'], result_dict['domain'] = groups[1], groups[2]
        print(result_dict)
    else:
        raise ValueError('not found')
```
>Над регуляркой особо не заморачивался

2021-12-10 12:45 UTC, DarkSou1 commented on lesson_8/task_1.py
> +def email_parse(email_adress):
С этим соглашусь)

2021-12-10 12:46 UTC, DarkSou1 commented on lesson_8/task_1.py
> +    if RE_EMAIL.match(email_adress) is not None:
Согласен, сейчас уже так не делаю, ide сама подсвечивает)

2021-12-10 12:50 UTC, DarkSou1 commented on lesson_8/task_1.py
> +
Когда делал домашку, до меня не дошло, что можно через группы, Первое что я нашел в интернете это был "split" @okunevkirill

2021-12-11 21:13 UTC, okunevkirill requested changes

2021-12-11 21:13 UTC, okunevkirill commented on lesson_8/task_4.py
> +        nonlocal func
Зачем это? - говорит о том что тебе ещё раз надо декораторы почитать

2021-12-11 21:13 UTC, okunevkirill commented on lesson_8/task_4.py
> +def val_checker(func):  # декорирующая функция с аргументом лямбда функции
Я бы назвал val_checker(`callback`)

2021-12-11 21:13 UTC, okunevkirill commented on lesson_8/task_4.py
> +                calk(*x)
В функцию должны передаваться как позиционные, так и ключевые аргументы

2021-12-11 21:13 UTC, okunevkirill commented on lesson_8/task_4.py
> +                raise ValueError(f'ValueError : wrong val {x[0]}')
Опять же, функция не возвращает ничего - должна возвращать результат исходной функции

2021-12-13 18:24 UTC, okunevkirill commented on lesson_8/task_3.py
> +        return f'{i ** 3}'
Бессмысленная функция - с таким же успехом у неё мог быть только 1 аргумент

2021-12-13 18:24 UTC, okunevkirill commented on lesson_8/task_3.py
> +    return wrapper
К самому декоратору вопросов нет - обычно реализуют как `args` так и `kwargs`

2021-12-13 18:24 UTC, okunevkirill commented on lesson_8/task_4.py
> +        def wrapper(*x):  # фунция с аргументом (который передан основной функции)
Желательно придерживаться стандартов по нейменгу (`args`)

2021-12-13 18:24 UTC, merged